runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg))$
  static_files: images/\1
  upload: images/.*\.(gif|png|jpg)$

- url: /.*
  script: not_found.php
